from typing import List

from PIL import Image

from raytracer.linalg import Vec3


def save_ppm(img: List[List[Vec3]], filename: str):
    f = open(filename, "w")
    f.write(f"P3 {len(img[0])} {len(img)} 255\n")
    # f.write("# Generated by raytracer\n")
    for i in range(len(img)):
        for j in range(len(img[0])):
            f.write(
                f"{int(img[i][j].x * 255)} {int(img[i][j].y * 255)} {int(img[i][j].z * 255)}\n"
            )
    f.close()


def save_png(img: List[List[Vec3]], filename: str):
    # save image to png file
    png = Image.new("RGB", (len(img[0]), len(img)))
    data = png.load()
    for i in range(len(img)):
        for j in range(len(img[0])):
            data[j, i] = (
                int(img[i][j].x * 255),
                int(img[i][j].y * 255),
                int(img[i][j].z * 255),
            )
    png.save(filename)
